//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cas.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_SERVICE_ACTIVITYLOG
    {
        public decimal ACTIVITYLOG_ID { get; set; }
        public string SERVICE_NAME { get; set; }
        public string SYSTEM_CODE { get; set; }
        public string RESPONSE_CODE { get; set; }
        public string RESPONSE_MESSAGE { get; set; }
        public string REQUEST_URL { get; set; }
        public Nullable<System.DateTime> REQUEST_DATETIME { get; set; }
        public string REQUEST_IPADDRESS { get; set; }
        public string REFERENCE_NO { get; set; }
        public string XML_REQUEST { get; set; }
        public string XML_RESPONSE { get; set; }
    }
}
