//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKCAR.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR_STATUS_MASTER
    {
        public string CAR_ID { get; set; }
        public System.DateTime CAR_TRAN_DATETIME { get; set; }
        public System.DateTime CAR_STATUS_DATETIME { get; set; }
        public string CAR_REFERNCE_NO { get; set; }
        public string CAR_CHANNEL_ID { get; set; }
        public string CAR_SUBSCRIPTION_ID { get; set; }
        public string CAR_SUBSCRIPTION_CUSTYPE { get; set; }
        public string CAR_SUBSCRIPTION_CARDTYPE { get; set; }
        public string CAR_PDM_PRODUCTGROUP_ID { get; set; }
        public string CAR_PDM_PRODUCTGROUP_DESC { get; set; }
        public string CAR_PDM_PRODUCTSUBGROUP_ID { get; set; }
        public string CAR_PDM_PRODUCTSUBGROUP_DESC { get; set; }
        public string CAR_PDM_PRODUCT_ID { get; set; }
        public string CAR_PDM_PRODUCT_DESC { get; set; }
        public string CAR_PDM_CAMPAIGN_ID { get; set; }
        public string CAR_PDM_CAMPAIGN_DESC { get; set; }
        public string CAR_STATUS_CODE { get; set; }
        public string CAR_STATUS_DESC { get; set; }
        public string CAR_SUBSTATUS_CODE { get; set; }
        public string CAR_SUBSTATUS_DESC { get; set; }
        public string CAR_UPDATED_BRANCH { get; set; }
        public string CAR_UPDATED_TEAM { get; set; }
        public string CAR_UPDATED_ID { get; set; }
        public string CAR_UPDATED_NAME { get; set; }
        public string CAR_UPDATED_POSITION { get; set; }
        public string CAR_REMARK { get; set; }
        public string CAR_CMT_PRODUCTGROUP_ID { get; set; }
        public string CAR_CMT_PRODUCTGROUP_DESC { get; set; }
        public string CAR_CMT_PRODUCT_ID { get; set; }
        public string CAR_CMT_PRODUCT_DESC { get; set; }
        public string CAR_CMT_CAMPAIGN_ID { get; set; }
        public string CAR_CMT_CAMPAIGN_DESC { get; set; }
    }
}
