//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKCAR.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR_STATUS_HISTORY
    {
        public string CAR_ID { get; set; }
        public decimal CAR_SEQ_ID { get; set; }
        public string CAR_OWNERSYSTEM_ID { get; set; }
        public string CAR_OWNERSYSTEM_CODE { get; set; }
        public string CAR_REFERENCESYSTEM_ID { get; set; }
        public string CAR_REFERENCESYSTEM_CODE { get; set; }
        public string CAR_STATUS_CODE { get; set; }
        public string CAR_STATUS_DESC { get; set; }
        public string CAR_SUBSTATUS_CODE { get; set; }
        public string CAR_SUBSTATUS_DESC { get; set; }
        public string CAR_UPDATED_BRANCH { get; set; }
        public string CAR_UPDATED_TEAM { get; set; }
        public string CAR_UPDATED_ID { get; set; }
        public string CAR_UPDATED_NAME { get; set; }
        public string CAR_UPDATED_POSITION { get; set; }
        public string CAR_REMARK { get; set; }
        public Nullable<System.DateTime> CAR_STATUS_DATETIME { get; set; }
        public Nullable<System.DateTime> CAR_CREATE_DATETIME { get; set; }
    }
}
