//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKCAR.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_SYSTEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAS_SYSTEM()
        {
            this.CAR_BATCH_SYSTEM_MAPPING = new HashSet<CAR_BATCH_SYSTEM_MAPPING>();
        }
    
        public string SYSTEM_ID { get; set; }
        public string SYSTEM_NAME { get; set; }
        public string SYSTEM_SECURITY_KEY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAR_BATCH_SYSTEM_MAPPING> CAR_BATCH_SYSTEM_MAPPING { get; set; }
    }
}
