//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKCAR.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_ROLE
    {
        public decimal ROLE_ID { get; set; }
        public string SYSTEM_ID { get; set; }
        public string CAS_SERVICE { get; set; }
        public string CAS_SCOPE { get; set; }
    }
}
