//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKCAR.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KKCAR.Common.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel ID.
        /// </summary>
        public static string Lbl_ChannelID {
            get {
                return ResourceManager.GetString("Lbl_ChannelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMT Campaign Description.
        /// </summary>
        public static string Lbl_CMTCampaignDesc {
            get {
                return ResourceManager.GetString("Lbl_CMTCampaignDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMT Campaign ID.
        /// </summary>
        public static string Lbl_CMTCampaignID {
            get {
                return ResourceManager.GetString("Lbl_CMTCampaignID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMT Product Description.
        /// </summary>
        public static string Lbl_CMTProductDesc {
            get {
                return ResourceManager.GetString("Lbl_CMTProductDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMT Production Group Description.
        /// </summary>
        public static string Lbl_CMTProductGroupDesc {
            get {
                return ResourceManager.GetString("Lbl_CMTProductGroupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMT Production Group ID.
        /// </summary>
        public static string Lbl_CMTProductGroupID {
            get {
                return ResourceManager.GetString("Lbl_CMTProductGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMT Product ID.
        /// </summary>
        public static string Lbl_CMTProductID {
            get {
                return ResourceManager.GetString("Lbl_CMTProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner System Code.
        /// </summary>
        public static string Lbl_OwnerSystemCode {
            get {
                return ResourceManager.GetString("Lbl_OwnerSystemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner System ID.
        /// </summary>
        public static string Lbl_OwnerSystemId {
            get {
                return ResourceManager.GetString("Lbl_OwnerSystemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDM Campaign Description.
        /// </summary>
        public static string Lbl_PDMCampaignDesc {
            get {
                return ResourceManager.GetString("Lbl_PDMCampaignDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDM Campaign ID.
        /// </summary>
        public static string Lbl_PDMCampaignID {
            get {
                return ResourceManager.GetString("Lbl_PDMCampaignID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDM Product Description.
        /// </summary>
        public static string Lbl_PDMProductDesc {
            get {
                return ResourceManager.GetString("Lbl_PDMProductDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDM Product Group Description.
        /// </summary>
        public static string Lbl_PDMProductGroupDesc {
            get {
                return ResourceManager.GetString("Lbl_PDMProductGroupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDM Product Group ID.
        /// </summary>
        public static string Lbl_PDMProductGroupID {
            get {
                return ResourceManager.GetString("Lbl_PDMProductGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDM Product ID.
        /// </summary>
        public static string Lbl_PDMProductID {
            get {
                return ResourceManager.GetString("Lbl_PDMProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDM Product Subgroup Description.
        /// </summary>
        public static string Lbl_PDMProductSubGroupDesc {
            get {
                return ResourceManager.GetString("Lbl_PDMProductSubGroupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDM Product Subgroup ID.
        /// </summary>
        public static string Lbl_PDMProductSubGroupID {
            get {
                return ResourceManager.GetString("Lbl_PDMProductSubGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No.
        /// </summary>
        public static string Lbl_RefNo {
            get {
                return ResourceManager.GetString("Lbl_RefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference System Code.
        /// </summary>
        public static string Lbl_RefSystemCode {
            get {
                return ResourceManager.GetString("Lbl_RefSystemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference System ID.
        /// </summary>
        public static string Lbl_RefSystemId {
            get {
                return ResourceManager.GetString("Lbl_RefSystemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string Lbl_Remark {
            get {
                return ResourceManager.GetString("Lbl_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        public static string Lbl_ServiceName {
            get {
                return ResourceManager.GetString("Lbl_ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Lbl_Status {
            get {
                return ResourceManager.GetString("Lbl_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status DateTime.
        /// </summary>
        public static string Lbl_StatusDateTime {
            get {
                return ResourceManager.GetString("Lbl_StatusDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Name.
        /// </summary>
        public static string Lbl_StatusName {
            get {
                return ResourceManager.GetString("Lbl_StatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Next Branch.
        /// </summary>
        public static string Lbl_StatusNextBranch {
            get {
                return ResourceManager.GetString("Lbl_StatusNextBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Next Team.
        /// </summary>
        public static string Lbl_StatusNextTeam {
            get {
                return ResourceManager.GetString("Lbl_StatusNextTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription CardType.
        /// </summary>
        public static string Lbl_SubsCardType {
            get {
                return ResourceManager.GetString("Lbl_SubsCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription CustomerType.
        /// </summary>
        public static string Lbl_SubsCusType {
            get {
                return ResourceManager.GetString("Lbl_SubsCusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription ID.
        /// </summary>
        public static string Lbl_SubsID {
            get {
                return ResourceManager.GetString("Lbl_SubsID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubStatus.
        /// </summary>
        public static string Lbl_SubStatus {
            get {
                return ResourceManager.GetString("Lbl_SubStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubStatus Name.
        /// </summary>
        public static string Lbl_SubStatusName {
            get {
                return ResourceManager.GetString("Lbl_SubStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Code.
        /// </summary>
        public static string Lbl_SystemCode {
            get {
                return ResourceManager.GetString("Lbl_SystemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction DateTime.
        /// </summary>
        public static string Lbl_TransactionDate {
            get {
                return ResourceManager.GetString("Lbl_TransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Branch.
        /// </summary>
        public static string Lbl_UpdatedBranch {
            get {
                return ResourceManager.GetString("Lbl_UpdatedBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated ID.
        /// </summary>
        public static string Lbl_UpdatedID {
            get {
                return ResourceManager.GetString("Lbl_UpdatedID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Name.
        /// </summary>
        public static string Lbl_UpdatedName {
            get {
                return ResourceManager.GetString("Lbl_UpdatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Position.
        /// </summary>
        public static string Lbl_UpdatedPosition {
            get {
                return ResourceManager.GetString("Lbl_UpdatedPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Team.
        /// </summary>
        public static string Lbl_UpdatedTeam {
            get {
                return ResourceManager.GetString("Lbl_UpdatedTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records Found.
        /// </summary>
        public static string Msg_NoRecords {
            get {
                return ResourceManager.GetString("Msg_NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid..
        /// </summary>
        public static string ValErr_InvalidData {
            get {
                return ResourceManager.GetString("ValErr_InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid date format..
        /// </summary>
        public static string ValErr_InvalidDateFormat {
            get {
                return ResourceManager.GetString("ValErr_InvalidDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string ValErr_RequiredField {
            get {
                return ResourceManager.GetString("ValErr_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot exceed {1} characters..
        /// </summary>
        public static string ValErr_StringLength {
            get {
                return ResourceManager.GetString("ValErr_StringLength", resourceCulture);
            }
        }
    }
}
