//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cas.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_SEARCH_SUBSCRIPTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAS_SEARCH_SUBSCRIPTION()
        {
            this.CAR_SEARCH_REFAPP = new HashSet<CAR_SEARCH_REFAPP>();
        }
    
        public string SUBSCRIPTION_ID { get; set; }
        public decimal SUBSCRIPTION_TYPE_ID { get; set; }
        public string KKCISID { get; set; }
        public string CISID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAR_SEARCH_REFAPP> CAR_SEARCH_REFAPP { get; set; }
    }
}
