truncate table CAR.CAS_SUBSCRIPTION_TYPE

INSERT INTO CAR.CAS_SUBSCRIPTION_TYPE(SUBSCRIPTION_TYPE_ID, SUBSCRIPTION_TYPE_NAME) VALUES('001','บัตรประจำตัวประชาชน');
INSERT INTO CAR.CAS_SUBSCRIPTION_TYPE(SUBSCRIPTION_TYPE_ID, SUBSCRIPTION_TYPE_NAME) VALUES('002','Passport');
INSERT INTO CAR.CAS_SUBSCRIPTION_TYPE(SUBSCRIPTION_TYPE_ID, SUBSCRIPTION_TYPE_NAME) VALUES('003','Tax ID');
INSERT INTO CAR.CAS_SUBSCRIPTION_TYPE(SUBSCRIPTION_TYPE_ID, SUBSCRIPTION_TYPE_NAME) VALUES('004','Corporate Registration');
INSERT INTO CAR.CAS_SUBSCRIPTION_TYPE(SUBSCRIPTION_TYPE_ID, SUBSCRIPTION_TYPE_NAME) VALUES('005','Bureaucracy ID');
INSERT INTO CAR.CAS_SUBSCRIPTION_TYPE(SUBSCRIPTION_TYPE_ID, SUBSCRIPTION_TYPE_NAME) VALUES('006','Government ID');
INSERT INTO CAR.CAS_SUBSCRIPTION_TYPE(SUBSCRIPTION_TYPE_ID, SUBSCRIPTION_TYPE_NAME) VALUES('007','Financial Institution');
INSERT INTO CAR.CAS_SUBSCRIPTION_TYPE(SUBSCRIPTION_TYPE_ID, SUBSCRIPTION_TYPE_NAME) VALUES('008','Other Juristic ID');
INSERT INTO CAR.CAS_SUBSCRIPTION_TYPE(SUBSCRIPTION_TYPE_ID, SUBSCRIPTION_TYPE_NAME) VALUES('009','บัตรประจำตัวต่างด้าว');
INSERT INTO CAR.CAS_SUBSCRIPTION_TYPE(SUBSCRIPTION_TYPE_ID, SUBSCRIPTION_TYPE_NAME) VALUES('010','เลขบริษัทต่างชาติ TRO');
INSERT INTO CAR.CAS_SUBSCRIPTION_TYPE(SUBSCRIPTION_TYPE_ID, SUBSCRIPTION_TYPE_NAME) VALUES('099','ไม่ใช้งาน');

--truncate table CAR.CAS_SUBSCRIPTION_TYPE
