//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKCAR.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR_BATCH_LOG_DETAIL
    {
        public decimal BATCH_LOG_DETAIL_ID { get; set; }
        public decimal BATCH_LOG_ID { get; set; }
        public string REFERENCE_NO { get; set; }
        public string CHANNEL_ID { get; set; }
        public string RESPONSE_CODE { get; set; }
        public string RESPONSE_MESSAGE { get; set; }
    
        public virtual CAR_BATCH_LOG CAR_BATCH_LOG { get; set; }
    }
}
