//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKCAR.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR_SYS_STATUS_CBS_FILE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAR_SYS_STATUS_CBS_FILE()
        {
            this.CAR_SYS_STATUS_CBS_FILE_DATA = new HashSet<CAR_SYS_STATUS_CBS_FILE_DATA>();
        }
    
        public decimal CAR_SYS_STATUS_CBS_FILE_ID { get; set; }
        public string CAR_FILENAME { get; set; }
        public string CAR_FILEPATH { get; set; }
        public System.DateTime CAR_FILE_CREATE_DATE { get; set; }
        public System.DateTime CAR_FILE_PROCESS_TIME { get; set; }
        public string CAR_PROCESS_STATUS { get; set; }
        public string CAR_PROCESS_ERROR_STEP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAR_SYS_STATUS_CBS_FILE_DATA> CAR_SYS_STATUS_CBS_FILE_DATA { get; set; }
    }
}
