//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cas.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_SUBSCRIPTION_CARDTYPE
    {
        public string SUBSCRIPTION_CARDTYPE_CODE { get; set; }
        public string SUBSCRIPTION_CARDTYPE_TH { get; set; }
        public string SUBSCRIPTION_CARDTYPE_EN { get; set; }
        public string SUBSCRIPTION_CARDTYPE_GROUP { get; set; }
        public string SUBSCRIPTION_CARDTYPE_STATUS { get; set; }
        public Nullable<System.DateTime> SUBSCRIPTION_CARDTYPE_START_DA { get; set; }
        public Nullable<System.DateTime> SUBSCRIPTION_CARDTYPE_END_DATE { get; set; }
        public string SUBSCRIPTION_CARDTYPE_SMA_CODE { get; set; }
    }
}
