//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cas.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_CAMPAIGN
    {
        public string CAMPAIGN_ID { get; set; }
        public string CAMPAIGN_NAME { get; set; }
    }
}
