alter table CAR.CAS_SUBSCRIPTION_TYPE
add SUBSCRIPTION_TYPE_ID_ varchar2(100);

update  CAR.CAS_SUBSCRIPTION_TYPE
set SUBSCRIPTION_TYPE_ID_=SUBSCRIPTION_TYPE_ID;

commit;

alter table CAR.CAS_SEARCH_TICKET
modify  SUBSCRIPTION_TYPE_ID_ varchar2(100) not null;


ALTER TABLE CAR.CAS_SUBSCRIPTION_TYPE
 DROP PRIMARY KEY CASCADE;

alter table CAR.CAS_SUBSCRIPTION_TYPE
drop column SUBSCRIPTION_TYPE_ID cascade constraints;

alter table CAR.CAS_SUBSCRIPTION_TYPE
rename column SUBSCRIPTION_TYPE_ID_ to SUBSCRIPTION_TYPE_ID;


ALTER TABLE CAR.CAS_SUBSCRIPTION_TYPE
ADD CONSTRAINT PK_CAS_SUBSCRIPTION_TYPE PRIMARY KEY (SUBSCRIPTION_TYPE_ID)
USING INDEX tablespace  "CARMASDATATBS";
