
alter table CAR.CAS_SEARCH_SUBSCRIPTION
add SUBSCRIPTION_TYPE_ID_ varchar2(100);

update CAR.CAS_SEARCH_SUBSCRIPTION
set SUBSCRIPTION_TYPE_ID_ = SUBSCRIPTION_TYPE_ID;

commit;

alter table CAR.CAS_SEARCH_SUBSCRIPTION
modify  SUBSCRIPTION_TYPE_ID_ varchar2(100) not null;




--Drop Current Primary Key
alter table CAR.CAS_SEARCH_SUBSCRIPTION
drop primary key cascade;


--Drop Column
alter table CAR.CAS_SEARCH_SUBSCRIPTION
drop column SUBSCRIPTION_TYPE_ID cascade constraints;

--Rename Temp Column
alter table CAR.CAS_SEARCH_SUBSCRIPTION
rename column SUBSCRIPTION_TYPE_ID_ to SUBSCRIPTION_TYPE_ID;

--Create Primary Key
ALTER TABLE CAR.CAS_SEARCH_SUBSCRIPTION
 ADD CONSTRAINT  CAS_SEARCH_SUBSCRIPTION_PK
 PRIMARY KEY
 (SUBSCRIPTION_ID, SUBSCRIPTION_TYPE_ID)
 USING INDEX tablespace  "CARMASDATATBS";