//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKCAR.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR_STATUS_REFFERENCE
    {
        public string CAR_ID { get; set; }
        public string CAR_SYSTEM_ID { get; set; }
        public string CAR_SYSTEM_CODE { get; set; }
    }
}
