//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKCAR.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_SEARCH_LEAD
    {
        public string LEAD_ID { get; set; }
        public string SUBSCRIPTION_ID { get; set; }
        public decimal SUBSCRIPTION_TYPE_ID { get; set; }
    }
}
